"""Type stubs for the Rust engine (`rust/src/`)."""

from types import TracebackType
from typing import Any, Callable, Generic, Protocol, TypeVar

T = TypeVar("T")

class _Observer(Protocol):
    def update(self) -> None: ...

class Signal(Generic[T]):
    def __init__(self, value: T, *, equal: Callable[[T, T], bool] | None = None) -> None: ...
    @property
    def value(self) -> T:
        """The current value.

        Getting this property returns the stored Python value. Setting it
        updates the stored value and notifies observers if the value changed.
        """
    @value.setter
    def value(self, value: T) -> None: ...
    @property
    def _value(self) -> T: ...
    @property
    def _version(self) -> int: ...
    _equal: Callable[[T, T], bool] | None
    _name: str
    def update(self) -> None:
        """Force a notification to all observers unconditionally."""
    def invalidate(self) -> None:
        """Force downstream recomputation; for a Signal, equivalent to `update`."""
    def notify(self) -> None:
        """Notify all observers by calling their update method."""
    def subscribe(self, observer: _Observer) -> None:
        """Subscribe an observer to this signal. The observer is held weakly."""
    def unsubscribe(self, observer: _Observer) -> None:
        """Unsubscribe an observer from this signal."""
    def _observer_count(self) -> int: ...
    def _restore(self, value: T, version: int) -> None: ...

class Computed(Generic[T]):
    def __init__(self, f: Callable[[], T], *, equal: Callable[[T, T], bool] | None = None) -> None: ...
    @property
    def value(self) -> T:
        """Get the current value, recomputing lazily when stale."""
    @property
    def _value(self) -> T: ...
    @property
    def _version(self) -> int: ...
    _equal: Callable[[T, T], bool] | None
    _name: str
    @property
    def _deps(self) -> tuple[Any, ...]: ...
    def update(self) -> None:
        """Mark this computed stale when notified by an upstream dependency."""
    def _invalidate(self) -> None: ...
    def notify(self) -> None:
        """Notify all observers by calling their update method."""
    def subscribe(self, observer: _Observer) -> None:
        """Subscribe an observer, evaluating first so it sees every later change."""
    def unsubscribe(self, observer: _Observer) -> None:
        """Unsubscribe an observer from this computed."""
    def _observer_count(self) -> int: ...
    def _restorable(self) -> bool: ...
    def _init_source(self, holder: Signal[Any]) -> None: ...
    def _arm_restore(self, value: Any, version: int, holder: Signal[Any], source: Any, source_version: int) -> None: ...

class Effect:
    def __init__(self, fn: Callable[[], None]) -> None: ...
    def update(self) -> None:
        """Schedule a run after dependency invalidation has finished."""
    def dispose(self) -> None:
        """Stop this effect, including any pending run. Safe to repeat."""
    @property
    def _deps(self) -> tuple[Any, ...]: ...
    @property
    def _active(self) -> bool: ...

class Config:
    hooks: Any
    migration_warnings: bool

config: Config

def push_untracked() -> None: ...
def pop_untracked() -> None: ...
def is_tracking() -> bool: ...
def has_changed(previous: Any, current: Any) -> bool: ...
def computed_call[C](cls: type[C], func: Callable[..., Any], args: tuple[Any, ...]) -> C: ...
def begin_batch() -> None: ...
def end_batch() -> None: ...
def flush() -> None: ...
def unref(value: Any) -> Any: ...
def is_reactive(obj: object) -> bool: ...

class Untracked:
    def __enter__(self) -> None: ...
    def __exit__(self, *exc: object) -> bool: ...

class Batch:
    def __enter__(self) -> None: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None
    ) -> bool: ...

class SignalAt:
    def __init__(self, signal: Signal[Any], value: Any) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *exc: object) -> bool: ...
