"""Type stubs for the Rust engine (`rust/src/lib.rs`)."""

from typing import Any, Callable, Protocol

class _Observer(Protocol):
    def update(self) -> None: ...

class Signal:
    def __init__(self, value: Any) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...
    @property
    def _value(self) -> Any: ...
    @property
    def _version(self) -> int: ...
    def update(self) -> None: ...
    def subscribe(self, observer: _Observer) -> None: ...
    def unsubscribe(self, observer: _Observer) -> None: ...
    def _observer_count(self) -> int: ...

class Computed:
    def __init__(self, f: Callable[..., Any], *, _op_args: tuple[Any, ...] | None = None) -> None: ...
    @property
    def value(self) -> Any: ...
    @property
    def _value(self) -> Any: ...
    @property
    def _version(self) -> int: ...
    def subscribe(self, observer: _Observer) -> None: ...
    def unsubscribe(self, observer: _Observer) -> None: ...
    def _observer_count(self) -> int: ...

def push_untracked() -> None: ...
def pop_untracked() -> None: ...
def _register_standard_types(types: list[type]) -> None: ...
